sudo reboot

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,55 +1,107 @@
 language: rust
 rust: nightly
-os:
-  - linux
-  - osx
-sudo: false
-cache:
-  - apt
-  - cargo
+# cache:
+#   - apt
+#   - cargo
+git:
+  depth: 10
+
+addons:
+  apt:
+    packages:
+      - gcc-multilib
+
 env:
   global:
-    - DOCS_RS_VERSION=nightly-2018-06-03
-  matrix:
-    -
+    - FMT_VERSION=nightly-2018-10-14
+    - CLIPPY_VERSION=nightly-2018-10-14
+    - DOCS_RS_VERSION=nightly-2018-10-14 # fails because of futures-preview-0.3.0-alpha.7 nightly-2018-06-03 # https://github.com/onur/docs.rs/blob/32102ce458b34f750ef190182116d9583491a64b/Vagrantfile#L50
+
 matrix:
   include:
     - os: linux
-      dist: trusty
-      env: MODE=debug
+      dist: precise
+      env: BUILD="" RUN="x86_64-unknown-linux-gnu x86_64-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="precise" # ;-Cpanic=abort;-Clinker=gold
     - os: linux
-      dist: trusty
-      sudo: required # https://docs.travis-ci.com/user/reference/overview/
-      env: MODE=release
+      dist: precise
+      env: BUILD="" RUN="i686-unknown-linux-gnu i686-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="precise" # ;-Cpanic=abort;-Clinker=gold
     - os: linux
       dist: trusty
       sudo: false
-      env: MODE=release
+      env: BUILD="" RUN="x86_64-unknown-linux-gnu x86_64-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="trusty" # ;-Cpanic=abort;-Clinker=gold
     - os: linux
-      dist: precise
-      env: MODE=release
+      dist: trusty
+      sudo: false
+      env: BUILD="" RUN="i686-unknown-linux-gnu i686-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="trusty" # ;-Cpanic=abort;-Clinker=gold
     - os: linux
-      env: TARGET=x86_64-unknown-linux-musl MODE=debug
+      dist: trusty
+      sudo: required # https://docs.travis-ci.com/user/reference/overview/
+      env: BUILD="" RUN="x86_64-unknown-linux-gnu x86_64-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="trusty" # ;-Cpanic=abort;-Clinker=gold
     - os: linux
-      env: TARGET=x86_64-unknown-linux-musl MODE=release
+      dist: trusty
+      sudo: required # https://docs.travis-ci.com/user/reference/overview/
+      env: BUILD="" RUN="i686-unknown-linux-gnu i686-unknown-linux-musl" RUSTFLAGS_VARIATIONS=";" DIST="trusty" # ;-Cpanic=abort;-Clinker=gold
     - os: osx
-      env: TARGET=x86_64-unknown-linux-musl RUSTFLAGS=-Zlinker-flavor=ld.lld MODE=debug NO_RUN=1
+      osx_image: xcode6.4 # https://docs.travis-ci.com/user/reference/osx/
+      env: BUILD="x86_64-unknown-linux-musl" RUN="x86_64-apple-darwin" RUSTFLAGS_VARIATIONS=";" # https://github.com/rust-lang/rust/pull/49219 ;-Cpanic=abort
     - os: osx
-      env: TARGET=x86_64-unknown-linux-musl RUSTFLAGS=-Zlinker-flavor=ld.lld MODE=release NO_RUN=1
-  exclude:
-    - env:
-before_script:
-  - if [ -n "$TARGET" ]; then rustup target add "$TARGET"; fi
-  - rustup component add rustfmt-preview
-  - rustup toolchain add $DOCS_RS_VERSION # https://docs.rs/about
-  - if [ -n "$TARGET" ]; then rustup target add --toolchain $DOCS_RS_VERSION "$TARGET"; fi
-script:
-  - rustc --version
-  - cargo fmt --version
-  - rustdoc --version
-  - cargo fmt -- --check
-  - cargo build --verbose --locked $(if [ -n "$TARGET" ]; then echo "--target $TARGET"; fi) $(if [ "$MODE" = "release" ]; then echo "--release"; fi)
-  - if [ "$NO_RUN" != "1" ]; then RUST_BACKTRACE=full cargo run -p test --bin test --locked $(if [ -n "$TARGET" ]; then echo "--target $TARGET"; fi) $(if [ "$MODE" = "release" ]; then echo "--release"; fi) -- --locked $(if [ -n "$TARGET" ]; then echo "--target $TARGET"; fi) $(if [ "$MODE" = "release" ]; then echo "--release"; fi); fi
-  - cargo +$DOCS_RS_VERSION doc --no-deps --locked $(if [ -n "$TARGET" ]; then echo "--target $TARGET"; fi) $(if [ "$MODE" = "release" ]; then echo "--release"; fi) &>/dev/null
+      osx_image: xcode6.4 # https://docs.travis-ci.com/user/reference/osx/
+      env: BUILD="i686-unknown-linux-musl" RUN="i686-apple-darwin" RUSTFLAGS_VARIATIONS=";" # https://github.com/rust-lang/rust/pull/49219 ;-Cpanic=abort
+    - os: osx
+      osx_image: xcode8.3
+      env: BUILD="x86_64-unknown-linux-musl" RUN="x86_64-apple-darwin" RUSTFLAGS_VARIATIONS=";" # ;-Cpanic=abort
+    - os: osx
+      osx_image: xcode8.3
+      env: BUILD="i686-unknown-linux-musl" RUN="i686-apple-darwin" RUSTFLAGS_VARIATIONS=";" # ;-Cpanic=abort
+    - os: osx
+      osx_image: xcode9.4
+      env: BUILD="x86_64-unknown-linux-musl" RUN="x86_64-apple-darwin" RUSTFLAGS_VARIATIONS=";" # ;-Cpanic=abort
+    - os: osx
+      osx_image: xcode9.4
+      env: BUILD="i686-unknown-linux-musl" RUN="i686-apple-darwin" RUSTFLAGS_VARIATIONS=";" # ;-Cpanic=abort
+
+before_script: |
+  ( set -o errexit;set -o pipefail; set -o xtrace;set -o nounset;
+    if [ "$TRAVIS_OS_NAME" = "linux" -a "${DIST-}" = "precise" ]; then
+      # Bump libstdc++6 for libLLVM-8svn.so which requires GLIBCXX_3.4.17 https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
+      sudo -E add-apt-repository -y ppa:ubuntu-toolchain-r/test
+      sudo -E apt-get update
+      sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install libstdc++6-4.7-dev
+    fi
+    for TARGET in $BUILD $RUN; do [ "$TARGET" = $(rustup target list | grep default | grep -o -e '^[^ ]\+') ] || travis_retry rustup target add "$TARGET"; done
+    travis_retry rustup toolchain add $FMT_VERSION
+    travis_retry rustup toolchain add $CLIPPY_VERSION
+    travis_retry rustup component add rustfmt-preview --toolchain $FMT_VERSION
+    travis_retry rustup component add clippy-preview --toolchain $CLIPPY_VERSION
+    travis_retry rustup toolchain add $DOCS_RS_VERSION
+    for TARGET in $BUILD $RUN; do [ "$TARGET" = $(rustup target list | grep default | grep -o -e '^[^ ]\+') ] || travis_retry rustup target add --toolchain $DOCS_RS_VERSION "$TARGET"; done
+  )
+script: |
+  ( set -o errexit;set -o pipefail; set -o xtrace;set -o nounset;
+    cargo +$FMT_VERSION fmt -- --check
+    RUSTFLAGS="-C target-cpu=native" cargo +$CLIPPY_VERSION clippy --all-targets --all-features -- -D warnings
+    OLD_IFS=$IFS IFS=";"; for RUSTFLAGS in $RUSTFLAGS_VARIATIONS; do ( IFS=$OLD_IFS
+      export RUSTFLAGS
+      for TARGET in $BUILD $RUN; do (
+        [ \( "$TRAVIS_OS_NAME" = "osx" -o \( "$TRAVIS_OS_NAME" = "linux" -a "${DIST-}" = "precise" \) \) -a \( "$TARGET" = "x86_64-unknown-linux-musl" -o "$TARGET" = "i686-unknown-linux-musl" \) ] && RUSTFLAGS="$RUSTFLAGS -C linker=rust-lld -Z linker-flavor=ld.lld"
+        cargo build --verbose --target "$TARGET" -p constellation-rs --test tester $(for test in tests/*.rs; do test=${test##*/}; ( echo -n " --test ${test%.*}"; ); done) --examples --all-features # --tests builds doctests, this hack doesn't
+        RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" cargo build --verbose --target "$TARGET" -p constellation-rs --test tester $(for test in tests/*.rs; do test=${test##*/}; ( echo -n " --test ${test%.*}"; ); done) --examples --all-features --release
+      ); done
+      for TARGET in $RUN; do (
+        [ \( "$TRAVIS_OS_NAME" = "osx" -o \( "$TRAVIS_OS_NAME" = "linux" -a "${DIST-}" = "precise" \) \) -a \( "$TARGET" = "x86_64-unknown-linux-musl" -o "$TARGET" = "i686-unknown-linux-musl" \) ] && RUSTFLAGS="$RUSTFLAGS -C linker=rust-lld -Z linker-flavor=ld.lld"
+        RUST_BACKTRACE=full cargo test --test tester --target "$TARGET" --all-features
+        RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo test --test tester --target "$TARGET" --all-features --release -- --release
+        # RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo bench --target "$TARGET" --all-features
+        [ ! -d examples ] || for example in examples/*; do example=${example##*/}; (
+          RUST_BACKTRACE=full cargo run --target "$TARGET" --example ${example%.*} --all-features
+          RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo run --target "$TARGET" --example ${example%.*} --all-features --release
+        ); done
+      ); done
+    ); done; IFS=$OLD_IFS
+    for TARGET in $BUILD $RUN; do
+      cargo +$DOCS_RS_VERSION doc --no-deps --target "$TARGET" --all-features --release &>/dev/null
+    done
+  )
+
 notifications:
   email: false
